package ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 * Game information panel
 */

public class InfoPane extends Pane {
    private JTextPane infoTextPane;
    private JPanel panel1;

    /**
     * @param infoFrame
     */
    public InfoPane(final JFrame infoFrame) {
        backButton = new JButton("Back");
        panel = new JPanel(new FlowLayout());
        panel.add(backButton);

        backButton.addMouseListener(new MouseAdapter() {

            public void mouseClicked(MouseEvent e) {
                infoFrame.dispose();
            }

        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        infoTextPane = new JTextPane();
        infoTextPane.setFont(new Font("Book Antiqua", Font.PLAIN, 12));
        infoTextPane.setText("In this educational game project, the user is left with a virus trying to enter a cell, and the user can save the cell by using certain organelles' functions. They can also try to save the cell after the infection as well, or help the surrounding cells to not get infected.  The options that the user have will be different for the pre-infection and post-infection stages. In the pre-infection stage, the user will try to stop the virus reaching the nucleus of the cell with various functions of different organelles. For instance, it can change the surface proteins to disable the virus to connect to the cell, or use certain proteins to attack the viral DNA produced by the mRNA of the host cell and the ribosomes. All of these functions will be dependent on the energy sources (ATP) produced by the mithochondria, which can get infected by the virus as well. In the post-infection stage, the focus will be on surrounding cells as well with the current cell. The cell can either try to sacrifice itself to save the other cells or it can try to remove the viral DNA from its own DNA by using proteins. Viruses will continue to come and as time passes more vigourous virus will start to appear. The objective of the game is to survive as long as possible. Each organelle needs time to produce the required component to attack the virus. Each type of virus is also different in terms of its strength, endurance and speed, as each organelle can also produce different compounds and have different abilities. Different organelles can work together, as well. Score will be the time of survival.");
        panel1.add(infoTextPane, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(50, 50), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
