package ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

/**
 * CS319: Object-Oriented Software Engineering Course Project
 * Project Virion
 * Author: Mert İNAN on 5.12.2016.
 * Version: 1.0
 * Description:
 */

public class MainMenu extends JFrame {
    private JButton playButton;
    private JButton highScoresButton;
    private JButton quitButton;
    private JButton toggleMusicButton;
    private JButton helpButton;
    private JTextPane virionTextPane;
    private JPanel menuPanel;
    private JLabel backgroundImage;

    //Icon instantiation
    private ImageIcon playIcon = new ImageIcon("/MenuScreen-PlayButton.png");
    private ImageIcon highScoresIcon = new ImageIcon("/MenuScreen-HighScoreButton.png");
    private ImageIcon quitIcon = new ImageIcon("/MenuScreen-QuitButton.png");
    private ImageIcon toggleMusicIcon = new ImageIcon("/MenuScreen-MusicButton.png");
    private ImageIcon helpIcon = new ImageIcon("/MenuScreen-HelpButton.png");

    private void createUIComponents() {
        playButton = new JButton(playIcon);
        highScoresButton = new JButton(highScoresIcon);
        quitButton = new JButton(quitIcon);
        toggleMusicButton = new JButton(toggleMusicIcon);
        helpButton = new JButton(helpIcon);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        menuPanel.setLayout(new GridLayoutManager(5, 2, new Insets(50, 200, 50, 200), -1, -1));
        menuPanel.setEnabled(true);
        playButton.setIcon(new ImageIcon(getClass().getResource("/MenuScreen-PlayButton.png")));
        playButton.setText("");
        menuPanel.add(playButton, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        highScoresButton.setIcon(new ImageIcon(getClass().getResource("/MenuScreen-HighScoreButton.png")));
        highScoresButton.setText("");
        menuPanel.add(highScoresButton, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        quitButton.setIcon(new ImageIcon(getClass().getResource("/MenuScreen-QuitButton.png")));
        quitButton.setText("");
        menuPanel.add(quitButton, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        toggleMusicButton.setIcon(new ImageIcon(getClass().getResource("/MenuScreen-MusicButton.png")));
        toggleMusicButton.setText("");
        menuPanel.add(toggleMusicButton, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        helpButton.setIcon(new ImageIcon(getClass().getResource("/MenuScreen-HelpButton.png")));
        helpButton.setText("");
        menuPanel.add(helpButton, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        virionTextPane.setFont(new Font("Roboto", Font.PLAIN, 48));
        virionTextPane.setText("Virion");
        menuPanel.add(virionTextPane, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return menuPanel;
    }
}
